export const GET_POKEDEX_DETAILS_FETCHING = "GET_POKEDEX_DETAILS_FETCHING";
export const GET_POKEDEX_DETAILS_SUCCESS = "GET_POKEDEX_DETAILS_SUCCESS";
export const GET_POKEDEX_DETAILS_ERROR = "GET_POKEDEX_DETAILS_ERROR";

export const GET_POKEDEX_SEARCH_FETCHING = "GET_POKEDEX_SEARCH_FETCHING";
export const GET_POKEDEX_SEARCH_SUCCESS = "GET_POKEDEX_SEARCH_SUCCESS";
export const GET_POKEDEX_SEARCH_ERROR  = "GET_POKEDEX_SEARCH_ERROR";
